- name: set prompt
  ansible.builtin.shell: set-prompt prometheus

- name: make a directory
  ansible.builtin.file:
    path: /opt
    state: directory
    owner: expense
    group: expense

- name: Download node exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    owner: expense
    group: expense
    remote_src: yes

- name: copy node exporter service
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: start service
  ansible.builtin.systemd_service:
    name: node_exporter
    state: started
    daemon_reload: true
    enabled: true


