- name: copy grafana repo
  ansible.builtin.template:
    path: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: install grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

 - name: copy grafna service
   ansible.builtin.template:
     path: grafan.service
     dest: /etc/systemd/system/grafana.service

- name: start grafana service
  ansible.builtin.systemd_service:
    name: grafana
    state: started
    daemon_reload: yes
    enabled: yes