- name: copy grafana repo
  ansible.builtin.template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo

- name: install grafana
  ansible.builtin.dnf:
    name: grafana
    state: installed

- name: copy grafna service
  ansible.builtin.template:
    src: grafana-server.service
    dest: /usr/lib/systemd/system/grafana-server.service

- name: start grafana service
  ansible.builtin.systemd_service:
    name: grafana
    state: started
    daemon_reload: yes
    enabled: yes