- name: copy repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: Replace a specific line in a file
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "^#server.port: 5601"
    line: "server.port: 5601"

- name: Replace a specific line in a file
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "^#server.host: localhost"
    line: "server.host: 0.0.0.0"



- name: start kibana service
  ansible.builtin.systemd_service:
    name: kibana
    state: started






