- name: copy repo
  ansible.builtin.templates:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: Replace a specific line in a file
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.host:0.0.0.0'
    line: 'server.host:0.0.0.0'

- name: Replace a specific line in a file
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.port:5601'
    line: 'server.port:5601'

- name: start kibana service
  ansible.builtin.systemd_service:
    name: kibana
    state: started






