format_version: 10
pipelines:
  artifactory:
    group: tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2ae7d73:
        git: https://github.com/pdevops78/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    environment_variables:
    APP_VERSION: ""
    secure_variables:
      vault_token: "AES:mZ+qHIsb9ddvEqRzXwhzNg==:RfB2FPPssxxlDbMBpiRzU5wcCd/4zG1VBfUGXW6CmEA="

    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            tools-job:
              timeout: 0
              tasks:
                - exec: { command: env }
                - exec: { command: ansible-playbook, arguments: [ "-i","artifactory-internal.pdevops78.online,","tools.yaml", "-e","tool_name=artifactory","-e","ansible_user=ec2-user","-e","ansible_password=DevOps321" ],run_if: passed }