- name: install python-jenkins
  ansible.builtin.pip:
    name: python-jenkins
    executable: pip3.9

- name: copy local to remote
  ansible.builtin.template:
    src: templates/jobs/pipeline-jobs.xml
    dest: /tmp/{{item}}.xml
  loop:
    - frontend
    - backend

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/{{item}}.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://34.229.214.95:8080
    user: admin
  loop:
    - frontend
    - backend

