- name: install python-jenkins
  ansible.builtin.pip:
    name: python-jenkins
    executable: pip3.9

- name: copy local to remote
  ansible.builtin.template:
    src: jobs/multibranch-pipeline.xml
    dest: /tmp/{{item}}.xml
  loop:
    - frontend
    - backend

- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/{{item}}.xml') }}"
    name: "{{item}}"
    password: admin123
    url: http://54.159.68.139:8080
    user: admin
  loop:
    - frontend
    - backend

