- name: set prompt
  ansible.builtin.shell: set-prompt prometheus

- name: create a user
  ansible.builtin.user:
    name: expense

- name: make a directory
  ansible.builtin.file:
    path: /opt
    state: directory
    owner: expense
    group: expense

- name: Download prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.53.4/prometheus-2.53.4.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: expense
    group: expense

- name: copy prometheus service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: copy prometheus scrape config
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-2.53.4.linux-amd64/prometheus.yml

- name: start prometheus service
  ansible.builtin.systemd_service:
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes



