- name: add a user
  ansible.builtin.user:
    name: artifactory

- name: make a folder
  ansible.builtin.file:
    path: /opt
    state: directory
    owner: artifactory
    group: artifactory

- name: copy artifactory repo
  ansible.builtin.template:
    src: jfrog.repo
    dest: /etc/yum.repos.d/frog-artifactory-rpms.repo
#
#- name: Download and unarchive artifactory repo
#  ansible.builtin.unarchive:
#    src: https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/oss/jfrog-artifactory-oss/7.21.5/jfrog-artifactory-oss-7.21.5-linux.tar.gz
#    dest: /opt
#    owner: artifactory
#    group: artifactory
#    remote_src: yes
#  become_user: artifactory

- name: Install Jfrog
  ansible.builtin.dnf:
    name: jfrog-artifactory-oss
    state: installed
    disable_gpg_check: true

- name: start artifactory service
  ansible.builtin.systemd_service:
    name: artifactory
    state: started
    enabled: yes
#    enabled: yes
#    daemon-reload: yes




